---@class Identifiers
---@field [string] string
---@field ip string
---@field xbl string
---@field live string
---@field fivem string
---@field steam string
---@field discord string
---@field license string
---@field license2 string

---@class Player
---@field id number
---@field ped integer
---@field name string
---@field coords vector3
---@field citizenid string
---@field health number
---@field armor number
---@field ping number
---@field identifiers Identifiers
---@field steamProfile string
---@field nearby? {players: Player[], count: number, admins: number}

---@class ReportData
---@field id string
---@field sender Player
---@field status "pending"|"claimed"|"closed"
---@field title string
---@field catagory number
---@field description string
---@field notes string[]
---@field created_on string|osdate
---@field claimed_on string|osdate
---@field closed_on string|osdate

---@class Report
---@field data ReportData
---@field getId fun(): string
---@field getSender fun(): Player
---@field getStatus fun(): "pending"|"claimed"|"closed"
---@field getTitle fun(): string
---@field getCatagory fun(): number
---@field getCatagoryName fun(): string
---@field getDescription fun(): string
---@field getNotes fun(): string[]
---@field getCreatedTime fun(): string
---@field getClaimedTime fun(): string
---@field getClosedTime fun(): string
---@field isActive fun(): boolean
---@field update fun(data: ReportData): Report
---@field setTitle fun(title: string): Report
---@field setCatagory fun(catagory: number): Report
---@field setDescription fun(description: string[]): Report
---@field addNote fun(note: string): Report
---@field removeNote fun(index: number): Report
---@field isActive fun(): boolean
---@field claim fun(): Report
---@field unclaim fun(): Report
---@field close fun(): Report
---@field reopen fun(): Report
